```mermaid
graph LR
    subgraph T1 [State]
        direction TB
        A1[Node 1] --> A2[Node 2]
        A2 --> A3[Node 3]
        A3 --> A4[Node 4]
    end

    subgraph T2 [Timeline]
        direction TB
        B1[Node 1] --> B2[Node 2]
        B2 --> B3[Node 3]
        B3 --> B4[Node 4]
    end

    B1 -.-> A3
    B2 -.-> A3
    B3 -.-> A4
    B4 -.-> A4
```
